### ISSUE TITLE
KiCad dialog defaults output filename without suffix

### ISSUE THREAD

**Issue by bootchk** [SchrodingersGat/KiBoM#1]
When I first tried it on Ubuntu, KiCad 4.0.2, the KiCad BOM dialog generated a command line for me without a suffix on the output file name i.e. "%O".  Then when you choose Generate button, it says it succeeded (the app returns 0, it should return -1) but there was no file generated and there was a message that the extension was not supported.

I think that the code should append a suffix if any passed suffix is not supported.  My reasoning is that for nieve users who don't know to change the command line, the program should do something reasonable.

I have forked and fixed and will submit a pull request.  Of course you can reject it.

BTW, thanks very much, I appreciate the lack of dependency on other Python packages and the feature set is just what I need for my use case: generating a BOM to submit to a vendor, grouped appropriately.

**Comment by SchrodingersGat** [comment]
All sorted, I think. Thanks for your contribution.
