### ISSUE TITLE
alt_wrap = 1 strange results, or at least missing documentation.

### ISSUE THREAD

**Issue by set-soft** [SchrodingersGat/KiBoM#116]
I don't get the idea of this option.
It introduces \n characters in the "References" column, this isn't a good idea for most formats:

- HTML/XML: white spaces are equivalent, no difference between ' ' and '\n'
- CSV: the \n isn't escaped and the row is cut. OpenOffice supports it, but I wonder if simpler programs can interpret it. Any program reading line by line will break.
- XLSX: in this case you have better options, like make the cell adjust to text.

In any case the documentation should state which formats are supposed to suport it and the fact that it only works with "use_alt = 1"

**Comment by SchrodingersGat** [comment]
I have never seen the use in this option either. The fact that it does not work in most file output formats, and provides only a modicum of usefulness, means that I'll just remove the option entirely - https://github.com/SchrodingersGat/KiBoM/pull/117
