### ISSUE TITLE
Micro prefix

### ISSUE THREAD

**Issue by set-soft** [SchrodingersGat/KiBoM#133]
While testinng the code I found that:

https://github.com/SchrodingersGat/KiBoM/blob/06a14866d8166cfa71ae8ac1a48bda0c160fb380/kibom/units.py#L16

Is using:
GREEK SMALL LETTER MU	U+03BC	GREEK SMALL LETTER MU	μ

But, at least for me, is more common to use:
MICRO SIGN	U+00B5	MICRO SIGN	µ

So I'm using:
```python
REFIX_MICRO = [u"μ", u"µ", "u", "micro"]
```
Which looks pretty lame, and I hope the cut & paste worked ;-), but includes both: the micro sign and the greek letter.

**Comment by SchrodingersGat** [comment]
Character encoding issues are the most infuriating! Can you submit a PR to fix this ? Cheers :)
