### ISSUE TITLE
Set column order

### ISSUE THREAD

**Issue by justyn** [SchrodingersGat/KiBoM#14]
It would be great to be able to specify the specific order of the columns from the bom.ini file.

Currently they tend to end up in an unsuitable order, and have to be manually rearranged every time the BOM is generated.

**Comment by trentks** [comment]
@SchrodingersGat 

I think #19 added this feature. So I don't see any reason that this issue can't be closed.

Cheers.

**Comment by SchrodingersGat** [comment]
Ok, thanks. @justyn if this has not been fixed to your liking please re-open.
