### ISSUE TITLE
xlsx output issue

### ISSUE THREAD

**Issue by blopblopblup** [SchrodingersGat/KiBoM#143]
Using KiBoM_CLI from within KiCad can't output xlsx : 
python "F:\programmes\KiCad\bin\scripting\plugins\KiBoM/KiBOM_CLI.py" "%I" "%O.xlsx"

Log : 
ERROR Error writing XLSX output
ERROR Error writing variant 'None'

I'm on windows 10, I have installed XlsxWriter and I have no issue with other output formats.

**Comment by niflostancu** [comment]
Hi,
I had the same problem. You didn't install xlsxwriter in the right environment (kicad comes with embedded python 2.7 installation on windows).
You need to open cmd (as Administrator), navigate to Kicad's installation dir (then bin/) and install it there:
```
cd "C:\Program Files\Kicad\bin"
python -mpip install xlsxwriter
```

**Comment by blopblopblup** [comment]
Thanks !
