### ISSUE TITLE
KiCad v7 DNP

### ISSUE THREAD

**Issue by hb-ondis** [SchrodingersGat/KiBoM#180]
I'm using KiCad v7 and mark components as Do Not Populate using the DNP attribute from Symbol Properties.

I can't get KiBoM to pick this DNP feature up, so my BOM shows all the parts, even those marked DNP in KiCad.

Is there a plan to include this DNP feature into KiBoM?

**Comment by LeonEngineering** [comment]
@hb-ondis agree: It would be nice with a new release supporting this using this new built-in attributes (and preferrably a suggestion/solution of how to deal with also using old way by use of fields simultaneously to support older designs)

**Comment by set-soft** [comment]
Regardless of changes in KiBoM, I'll suggest trying [KiBot](https://github.com/INTI-CMNB/KiBot). 
It has KiBoM support (for legacy projects) and also an internal BoM that was based on KiBoM functionality and added a lot interesting features. You can use KiBoM variants, DNPs and also v7 DNP flag.

**Comment by SchrodingersGat** [comment]
@hb-ondis this is now implemented in the latest release :)
