### ISSUE TITLE
Include Multiple Manufacturers and Part Numbers

### ISSUE THREAD

**Issue by dbeckwith01** [SchrodingersGat/KiBoM#193]
What's the best way to include alternate manufacturers and part numbers for a part and have KiBoM place this is the BOM?  For example I have MFG and MPN as fields on all parts but for some I want to add MFG1 and MPN1 in addition to MFG and MPN.  I looked at using the REGEX but that seems more for including or excluding particular parts.

Thanks,

**Comment by SchrodingersGat** [comment]
You can always just add this information as extra fields?

**Comment by dbeckwith01** [comment]
Ok thank you for that.  I assume I have to add those extra field names to the `[COLUMN_ORDER]` in `bom.ini` so they are written out?

**Comment by SchrodingersGat** [comment]
They should be written out by default, `COLUMN_ORDER` is only if you want to rearrange them
