### ISSUE TITLE
"Exclude from Bill of Materials" Still Included In the BOM

### ISSUE THREAD

**Issue by dbeckwith01** [SchrodingersGat/KiBoM#194]
I have several parts, SMD jumper pads and a Tag connect connector footprint marked with "Exclude from bill of materials" checked in the Symbol Properties but they still appear in KiBoM output.  Is there anyway to have KiBoM respect this flag?

**Comment by SchrodingersGat** [comment]
@dbeckwith01 are you using the latest version? I have just checked with a sample schematic, and the component is not included in the generated BOM when `Exclude from bill of materials` is checked

**Comment by dbeckwith01** [comment]
Hi @SchrodingersGat I'm using KiBot v1.6.3 in Docker via `docker pull setsoft/kicad_auto:ki7`

**Comment by SchrodingersGat** [comment]
@dbeckwith01 can you confirm that the version `1.9.0` is being run, and that there's not some other version of the library installed?

**Comment by dbeckwith01** [comment]
@set-soft 

Thank you for the help.  I'm new to using KiBot and KiBoM to produce my fabrication outputs.  Would you like me to open an issue in KiBoT with these details and include my KiBoT configuration?

**Comment by set-soft** [comment]
Hi @dbeckwith01 !

Yes, and include a small example, just a few components where we can expose the issue.

**Comment by set-soft** [comment]
Hi @dbeckwith01 !

Yes, and include a small example, just a few components where we can expose the issue.

**Comment by SchrodingersGat** [comment]
Closed by #197
