### ISSUE TITLE
group_connectors option doesn't work

### ISSUE THREAD

**Issue by cvt1982** [SchrodingersGat/KiBoM#23]
I cannot get the **group_connectors** option in the _bom.ini_ to work.
As I understand it "value" field is ignored for components who is of type "connector".
I don't know the exact mechanism, but trying to search for the group_connectors option ended in the preferences.py file.
Also if I look in your example schematic you have 2 connectors (P1 and P2), and they are having separate lines in your example .html and .csv output files.
Do you have to give connectors a special field to mark them as "connectors"??

**Comment by SchrodingersGat** [comment]
Hi @cvt1982 I don't think this is implemented yet, or has been disabled...
