### ISSUE TITLE
Provide a packaging method

### ISSUE THREAD

**Issue by antoniovazquezblanco** [SchrodingersGat/KiBoM#24]
It would be nice if this program could be packaged so that users could install it just by using easy_install, pip or other packaging tools.

**Comment by SchrodingersGat** [comment]
Hi @antoniovazquezblanco are you willing to submit a PR for this? I'm not sure how to implement this :)

**Comment by antoniovazquezblanco** [comment]
I have never done this. I may be willing to do it in the future if I find more time but I cannot do it in the time being.

Thanks for the fast response.
