### ISSUE TITLE
Ignore virtual components

### ISSUE THREAD

**Issue by leoheck** [SchrodingersGat/KiBoM#41]
Virtual footprints should be ignored by default. I suggest a flag (`-a`) to show all.
For example, I have a footprint that is a logo. It should not be on BOM because I don't need to by a logo :)

**Comment by easyw** [comment]
virtual footprints are often used to show/hide mechanical parts (i.e. enclosure, standoff etc.) and they need to be in BOM list.

**Comment by SchrodingersGat** [comment]
@leoheck you can add a filter to the bom settings file to remove any items you do not want to appear in the bom output. This is pretty flexible and should allow you to achieve what you want. As @easyw says there are certainly good reasons for including parts that don't actually have a footprint associated.

**Comment by leoheck** [comment]
@SchrodingersGat thanks for pointing me that..

**Comment by leoheck** [comment]
I am using `[REGEX_EXCLUDE]` and it works fine, thanks.

But why it is tab separated? 

It took me a while to make it work and I fixed it even before I could find this comment:
`; Format is: "ColumName	Regex" (tab-separated)`

The best thing to do is to use whitespace separated (spaces, tabs)*

**Comment by SchrodingersGat** [comment]
Whitespace does make sense. Submit a PR and I'll merge the heck out of it :)

**Comment by KarlZeilhofer** [comment]
> But why it is tab separated?

Perhaps because a regex can contain space characters, but not tabulators?

**Comment by leoheck** [comment]
What? I didn't get it.

**Comment by leoheck** [comment]
@KarlZeilhofer I see what you said now. I think it is not a big issue.

**Comment by SchrodingersGat** [comment]
Closed by https://github.com/SchrodingersGat/KiBoM/pull/61
