### ISSUE TITLE
elide leading white space in values

### ISSUE THREAD

**Issue by bootchk** [SchrodingersGat/KiBoM#5]
I tried uploading my bom.csv to Digikey using their "BOM Manager" web app.  My file included leading white space in my "Digikey Part Number" (or "SKU") column (my bad, probably faulty cut-and-paste from Digikey catalog to KiCad) and Digikey failed to find a match.  So the request is: eliminate leading whitespace on values.

I would have thought Digikey would ignore it.  In the Digikey app, one can easily delete the whitespace and find a match, its not a big problem.

I might have a chance to fix the issue before ordering my next board.

**Comment by SchrodingersGat** [comment]
This is a good idea - I have updated the code to automatically strip out leading/trailing whitespace. Let me know if the additions work as you expect.
