### ISSUE TITLE
New preferences in README have lower camel case instead of snake case.

### ISSUE THREAD

**Issue by hraftery** [SchrodingersGat/KiBoM#71]
The new preferences `hideHeaders` and `hidePcbInfo` are described in the example config file in the README as such. To get them to work I had to use the keywords `hide_headers` and `hide_pcb_info` instead.

This appeared to happen here: https://github.com/SchrodingersGat/KiBoM/commit/08b2338326b0fdfdd6df240d802b5d536eafd2cb

**Comment by SchrodingersGat** [comment]
Fixed in #72
