### ISSUE TITLE
Consider adding license

### ISSUE THREAD

**Issue by kylemanna** [SchrodingersGat/KiBoM#9]
Stumbled on your repo and am excited with what I've found so far, but have one request:

Can you add a license so I can understand how I can use it?

I might suggest MIT license if you want to be openly permissive, quick overview at [tl;dr legal](https://tldrlegal.com/license/mit-license)

Thanks!

**Comment by SchrodingersGat** [comment]
Good idea )

**Comment by SchrodingersGat** [comment]
(I have added it under license.md)
